In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('one_hot.csv')
df.head()

   ID  Gender       City  Education Department ExperienceLevel
0   1    Male      Delhi  Bachelors         IT        Beginner
1   2  Female     Mumbai    Masters         HR    Intermediate
2   3    Male       Pune  Bachelors    Finance        Advanced
3   4  Female      Delhi        PhD         IT          Expert
4   5    Male  Bangalore    Masters  Marketing    Intermediate

In [3]:
df['Education'].value_counts()

Education
Bachelors    8
Masters      8
PhD          4
Name: count, dtype: int64

In [4]:
pd.get_dummies(df,columns=['Gender'])

,ID,City,Education,Department,ExperienceLevel,Gender_Female,Gender_Male
0,1,Delhi,Bachelors,IT,Beginner,False,True
1,2,Mumbai,Masters,HR,Intermediate,True,False
2,3,Pune,Bachelors,Finance,Advanced,False,True
3,4,Delhi,PhD,IT,Expert,True,False
4,5,Bangalore,Masters,Marketing,Intermediate,False,True
5,6,Chennai,Bachelors,HR,Beginner,True,False
6,7,Hyderabad,Masters,Finance,Advanced,False,True
7,8,Pune,Bachelors,IT,Intermediate,True,False
8,9,Mumbai,PhD,Marketing,Expert,False,True
9,10,Bangalore,Masters,HR,Advanced,True,False
10,11,Delhi,Bachelors,Finance,Beginner,False,True
11,12,Chennai,Masters,IT,Intermediate,True,False
12,13,Pune,PhD,HR,Expert,False,True
13,14,Mumbai,Bachelors,Marketing,Beginner,True,False
14,15,Bangalore,Masters,IT,Advanced,False,True
15,16,Hyderabad,Bachelors,Finance,Intermediate,True,False
16,17,Delhi,Masters,HR,Advanced,False,True
17,18,Pune,PhD,IT,Expert,True,False
18,19,Mumbai,Bachelors,Marketing,Beginner,False,True
19,20,Chennai,Masters,Finance,Intermediate,True,False

In [5]:
pd.get_dummies(df,columns=['Gender'],drop_first=True)

    ID       City  Education Department ExperienceLevel  Gender_Male
0    1      Delhi  Bachelors         IT        Beginner         True
1    2     Mumbai    Masters         HR    Intermediate        False
2    3       Pune  Bachelors    Finance        Advanced         True
3    4      Delhi        PhD         IT          Expert        False
4    5  Bangalore    Masters  Marketing    Intermediate         True
5    6    Chennai  Bachelors         HR        Beginner        False
6    7  Hyderabad    Masters    Finance        Advanced         True
7    8       Pune  Bachelors         IT    Intermediate        False
8    9     Mumbai        PhD  Marketing          Expert         True
9   10  Bangalore    Masters         HR        Advanced        False
10  11      Delhi  Bachelors    Finance        Beginner         True
11  12    Chennai    Masters         IT    Intermediate        False
12  13       Pune        PhD         HR          Expert         True
13  14     Mumbai  Bachelors  Marketing        Beginner        False
14  15  Bangalore    Masters         IT        Advanced         True
15  16  Hyderabad  Bachelors    Finance    Intermediate        False
16  17      Delhi    Masters         HR        Advanced         True
17  18       Pune        PhD         IT          Expert        False
18  19     Mumbai  Bachelors  Marketing        Beginner         True
19  20    Chennai    Masters    Finance    Intermediate        False

In [6]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=42)
x_train.head()

    ID  Gender     City  Education
8    9    Male   Mumbai        PhD
5    6  Female  Chennai  Bachelors
11  12  Female  Chennai    Masters
3    4  Female    Delhi        PhD
18  19    Male   Mumbai  Bachelors

In [7]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

x_train_encoded = ohe.fit_transform(x_train[['Gender']]).toarray()

x_test_encoded = ohe.transform(x_test[['Gender']]).toarray()

In [8]:
x_train_encoded

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [9]:
np.hstack([x_train[['City','Education']].values, x_train_encoded])

array([['Mumbai', 'PhD', 0.0, 1.0],
       ['Chennai', 'Bachelors', 1.0, 0.0],
       ['Chennai', 'Masters', 1.0, 0.0],
       ['Delhi', 'PhD', 1.0, 0.0],
       ['Mumbai', 'Bachelors', 0.0, 1.0],
       ['Delhi', 'Masters', 0.0, 1.0],
       ['Mumbai', 'Bachelors', 1.0, 0.0],
       ['Pune', 'Bachelors', 0.0, 1.0],
       ['Bangalore', 'Masters', 1.0, 0.0],
       ['Chennai', 'Masters', 1.0, 0.0],
       ['Bangalore', 'Masters', 0.0, 1.0],
       ['Pune', 'PhD', 0.0, 1.0],
       ['Pune', 'Bachelors', 1.0, 0.0],
       ['Delhi', 'Bachelors', 0.0, 1.0],
       ['Bangalore', 'Masters', 0.0, 1.0],
       ['Hyderabad', 'Masters', 0.0, 1.0]], dtype=object)

In [10]:
df.head()

   ID  Gender       City  Education Department ExperienceLevel
0   1    Male      Delhi  Bachelors         IT        Beginner
1   2  Female     Mumbai    Masters         HR    Intermediate
2   3    Male       Pune  Bachelors    Finance        Advanced
3   4  Female      Delhi        PhD         IT          Expert
4   5    Male  Bangalore    Masters  Marketing    Intermediate

In [11]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=42)
# x_train
from sklearn.model_selection import train_test_split

X = df.drop('Department', axis=1)
y = df['Department']

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
x_train

    ID  Gender       City  Education ExperienceLevel
13  14  Female     Mumbai  Bachelors        Beginner
8    9    Male     Mumbai        PhD          Expert
11  12  Female    Chennai    Masters    Intermediate
17  18  Female       Pune        PhD          Expert
6    7    Male  Hyderabad    Masters        Advanced
14  15    Male  Bangalore    Masters        Advanced
12  13    Male       Pune        PhD          Expert
19  20  Female    Chennai    Masters    Intermediate
0    1    Male      Delhi  Bachelors        Beginner
15  16  Female  Hyderabad  Bachelors    Intermediate
2    3    Male       Pune  Bachelors        Advanced
3    4  Female      Delhi        PhD          Expert
16  17    Male      Delhi    Masters        Advanced
4    5    Male  Bangalore    Masters    Intermediate
9   10  Female  Bangalore    Masters        Advanced
7    8  Female       Pune  Bachelors    Intermediate

In [12]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[
    ('tran1',OrdinalEncoder(categories=[['Bachelors','Masters','PhD'],['Beginner','Intermediate','Advanced','Expert']]),['Education','ExperienceLevel']),
    ('tran2',OneHotEncoder(drop='first'),['Gender','City'])
], remainder='passthrough')

In [13]:
ct.fit_transform(x_train)
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('tran1',
                                 OrdinalEncoder(categories=[['Bachelors',
                                                             'Masters', 'PhD'],
                                                            ['Beginner',
                                                             'Intermediate',
                                                             'Advanced',
                                                             'Expert']]),
                                 ['Education', 'ExperienceLevel']),
                                ('tran2', OneHotEncoder(drop='first'),
                                 ['Gender', 'City'])])