In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('ola.csv')
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,#NAME?,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,NaN,No,NaN,158,Cash,13,4.1,4.0,#NAME?,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?,NaN
3,2024-07-22 3:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,NaN,NaN,NaN,384,NaN,0,NaN,NaN,#NAME?,NaN
4,2024-07-02 9:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,NaN,No,NaN,822,Credit Card,45,4.0,3.0,#NAME?,NaN

In [4]:
df_clean = df[df['Booking_Status']=='Success'].dropna(subset=['V_TAT','Ride_Distance','Booking_Value'])
df_clean.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,NaN,No,NaN,158,Cash,13,4.1,4.0,#NAME?,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?,NaN
4,2024-07-02 9:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,NaN,No,NaN,822,Credit Card,45,4.0,3.0,#NAME?,NaN
5,2024-07-13 4:42:00,04:42:00,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,...,NaN,No,NaN,173,UPI,41,3.4,4.6,#NAME?,NaN
6,2024-07-23 9:51:00,09:51:00,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,...,NaN,No,NaN,140,Cash,49,3.2,4.5,#NAME?,NaN

In [5]:
#define input and output variables
x=df_clean[['Ride_Distance','V_TAT','C_TAT']]
y=df_clean['Booking_Value']
#split the data into training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print("Training set size:", x_train.shape)
print("Testing set size:", x_test.shape)
#Standerization
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

Training set size: (51173, 3)
Testing set size: (12794, 3)

In [6]:
scaler.mean_

array([ 22.82422371, 170.73198757,  84.79930823])

In [7]:
x_train_scaled=pd.DataFrame(x_train_scaled,columns=x_train.columns)
x_test_scaled=pd.DataFrame(x_test_scaled,columns=x_test.columns)
x_train_scaled.head()
x_test_scaled.head()

   Ride_Distance     V_TAT     C_TAT
0       0.573330  0.832744 -0.688878
1       1.555085 -0.380446  0.561137
2       0.643455  1.179369 -0.966659
3      -0.127924  1.439338  0.283356
4       0.503204  1.612651  0.838918

In [8]:
np.round(x_train.describe(),2)

       Ride_Distance     V_TAT    C_TAT
count       51173.00  51173.00  51173.0
mean           22.82    170.73     84.8
std            14.26     80.78     36.0
min             1.00     35.00     25.0
25%            10.00     98.00     55.0
50%            21.00    168.00     85.0
75%            35.00    238.00    115.0
max            49.00    308.00    145.0

In [9]:
np.round(x_train_scaled.describe())

       Ride_Distance    V_TAT    C_TAT
count        51173.0  51173.0  51173.0
mean            -0.0     -0.0      0.0
std              1.0      1.0      1.0
min             -2.0     -2.0     -2.0
25%             -1.0     -1.0     -1.0
50%             -0.0     -0.0      0.0
75%              1.0      1.0      1.0
max              2.0      2.0      2.0

In [16]:
# from sklearn.linear_model import LogisticRegression
# lr=LogisticRegression()
# lr_scaled=LogisticRegression()

# lr_scaled.fit(x_train_scaled,y_train)

# LogisticRegression()

# y_pred=lr.predict(x_test)
# y_pred_scaled=lr_scaled.predict(x_test_scaled)

# from sklearn.metrics import accuracy_score

# print("Accuracy without scaling:",accuracy_score(y_test,y_pred))
# print("Accuracy with scaling:",accuracy_score(y_test,y_pred_scaled))

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X = df_clean[['Ride_Distance','V_TAT','C_TAT']]
df_clean['Booking_Class'] = np.where(df_clean['Booking_Value'] > 500, 1, 0)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled, y_train)

y_pred = lr.predict(X_test_scaled)

# print("Accuracy:", accuracy_score(y_test, y_pred))
print("Accuracy without scaling:",accuracy_score(y_test,y_pred))
print("Accuracy with scaling:",accuracy_score(y_test,y_pred))

Accuracy without scaling: 0.001563232765358762
Accuracy with scaling: 0.001563232765358762