In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv('dt.csv')
df.head()

   Ride_Distance  V_TAT  C_TAT  Booking_Value
0            2.5      5      7          120.0
1            3.1      6      8          150.0
2            4.0      7      9          180.0
3            5.2      8     10          220.0
4            6.0      9     11          260.0

In [6]:
df.describe()

       Ride_Distance      V_TAT      C_TAT  Booking_Value
count      46.000000  46.000000  46.000000      45.000000
mean       24.778261  27.500000  29.500000     963.777778
std        13.485579  13.422618  13.422618     519.730214
min         2.500000   5.000000   7.000000     120.000000
25%        13.475000  16.250000  18.250000     520.000000
50%        24.700000  27.500000  29.500000     960.000000
75%        35.850000  38.750000  40.750000    1400.000000
max        47.800000  50.000000  52.000000    1840.000000

In [9]:
x_train, x_test, y_train, y_test = train_test_split(df.drop('Booking_Value', axis=1), df['Booking_Value'], test_size=0.2, random_state=42)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((36, 3), (10, 3), (36,), (10,))

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

#transform train and test sets
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [11]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns=x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns=x_test.columns)

In [12]:
np.round(x_train.describe(), 2)

       Ride_Distance  V_TAT  C_TAT
count          36.00  36.00  36.00
mean           24.44  27.17  29.17
std            12.91  12.88  12.88
min             2.50   5.00   7.00
25%            15.02  17.50  19.50
50%            23.85  26.50  28.50
75%            34.35  37.25  39.25
max            47.80  50.00  52.00

In [13]:
np.round(x_train_scaled.describe(), 2)

       Ride_Distance  V_TAT  C_TAT
count          36.00  36.00  36.00
mean            0.48   0.49   0.49
std             0.28   0.29   0.29
min             0.00   0.00   0.00
25%             0.28   0.28   0.28
50%             0.47   0.48   0.48
75%             0.70   0.72   0.72
max             1.00   1.00   1.00